print("******************************")
print("*        MY PROFILE         *")
print("******************************")
print("* Name    : Mrunal Ghogare   *")
print("* Age     : 18              *")
print("* Course  : Computer Science*")
print("* College : MVLU            *")
print("* City    : ANDHERI,Mumbai          *")
print("******************************")
